### ISSUE TITLE
Sms spoof not work

### ISSUE THREAD

**Issue by ERROR4317** [Gameye98/santet-online#1]
Traceback (most recent call last):
  File "santet.py", line 30, in <module>
    sms_spoof_elk()
  File "/data/data/com.termux/files/home/santet-online/core/onlen.py", line 141, in sms_spoof_elk
    print r.json()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by rnayabed** [comment]
this program uses 46elks.com API messaging service for sending messages. You need to create an account and purchase a pack to be able to send messages. Since you're not supplying a correct username and password, it is not returning a JSON response for which the application crashes!

**Comment by rnayabed** [comment]
I added the exception handler and form validation too :)
