### ISSUE TITLE
Spam Telegram Bermasalah.

### ISSUE THREAD

**Issue by BJS611** [Gameye98/santet-online#9]
Tolong perbahiki....
Trimakasih

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/santet.py", line 248, in <module>
    client.send_message(target, urmsg)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/messages.py", line 767, in send_message
    entity = await self.get_input_entity(entity)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 569, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "Jeff"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/santet.py", line 285, in <module>
    print("\n[!] Error: "+e)
TypeError: can only concatenate str (not "ValueError") to str

**Comment by wasert123** [comment]
لا اعرف  كيفية اصلاح الاخطاء

**Comment by wasert123** [comment]
اريد  حل المشكلة

**Comment by wasert123** [comment]
اريد  حل المشكلة
